project:
  type: website
  output-dir: docs

website:
  title: "밝은방"
  navbar:
   left:
      - text: 소개
        href: about.qmd    
      - text: 예술워크숍
        href: workshops.qmd
      - text: 기획 및 원고
        href: projects.qmd
      - text: 소식
        href: news.qmd
   right:
##      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: litera
    css: styles.css

editor: visual

